# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - <windows web app name>

on:
  push:
    branches:
      - master
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   YOUR_AZURE_APPSERVICE_PUBLISHPROFILE
#
# 2. Change these variables for your configuration:
env:
  YOUR_AZURE_WEBAPP_NAME: "shristi-admin" # set this to your application's name
  YOUR_AZURE_WEBAPP_SLOT_NAME: Production # set this to your application's slot name
  YOUR_AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  YOUR_NODE_VERSION: "20.x" # set this to the node version to use
  YOUR_ZIP_PACKAGE_NAME: "app-release.zip"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.YOUR_NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      - name: Zip artifact to upload
        run: 7z a ${{ env.YOUR_ZIP_PACKAGE_NAME }} ${{ env.YOUR_AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.YOUR_AZURE_WEBAPP_NAME }}
          path: ${{ env.YOUR_AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.YOUR_ZIP_PACKAGE_NAME }}
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.YOUR_AZURE_WEBAPP_NAME }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.YOUR_AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.YOUR_AZURE_WEBAPP_SLOT_NAME }}
          publish-profile: ${{ secrets.YOUR_AZURE_APPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.YOUR_AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.YOUR_ZIP_PACKAGE_NAME }}
